version: '3.7'
services:
  tws:
    build: .
    # restart: always
    ports:
      - "4002:4002"
      - "4003:4003"
      - "5901:5900"
    # volumes: 
    #   - ./ib/jts.ini:/root/Jts/ibgateway/978/jts.ini
    #   - ./ib/ibgateway.vmoptions:/root/Jts/ibgateway/978/ibgateway.vmoptions

    environment:
      - TZ=America/New_York
      - VNC_PASSWORD=1234 # CHANGEME

      # required for ibc
      - TWS_MAJOR_VRSN=981
      - LOG_PATH=~/ibc/logs
      - IBC_INI=/opt/ibc/config.ini
      - IBC_PATH=/opt/ibc
      - APP=GATEWAY

      # optional for IBC
      # - JAVA_PATH=/usr/local/i4j_jres/1.8.0_152-tzdata2019c/bin # JRE is bundled starting with TWS 
      - TWOFA_TIMEOUT_ACTION=exit
      - TRADING_MODE=paper
      # - TWS_PATH=~/Jts
      # - TWS_SETTINGS_PATH=
      - TWSUSERID=${TWSUSERID}
      - TWSPASSWORD=${TWSPASSWORD}
      # - FIXUSERID=
      # - FIXPASSWORD=
      # - HIDE=      